export enum BookingStatus {
  CREATED = "CREATED",

  PAYMENT_PENDING = "PAYMENT_PENDING",
  PAID_PENDING_PICKUP = "PAID_PENDING_PICKUP",
  PAYMENT_FAILED = "PAYMENT_FAILED",

  PICKUP_STARTED = "PICKUP_STARTED",
  IN_TRANSIT = "IN_TRANSIT",

  DELIVERED = "DELIVERED",

  CANCELLED_BEFORE_PICKUP = "CANCELLED_BEFORE_PICKUP",
  CANCELLED_AFTER_PICKUP = "CANCELLED_AFTER_PICKUP",

  REFUNDED = "REFUNDED",
  SETTLED = "SETTLED",
}
